name: na_hive_bloc
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons:
  hive:
  hive_flutter:
  intl:
  flutter_bloc:
  equatable:
  firebase_core: ^3.5.0
  firebase_auth:
  google_sign_in:
  firebase_database: ^11.1.3
  flutter_secure_storage: ^9.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner:
  hive_generator:
  

flutter:
  uses-material-design: true
