// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWWPwoSKyElhciL-DLz_Dg1m-_zD1Qm0E',
    appId: '1:838682859343:android:92cf6a3d4e354d271e973a',
    messagingSenderId: '838682859343',
    projectId: 'na-hive-pg',
    databaseURL: 'https://na-hive-pg-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'na-hive-pg.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGv4s-rTNdnCufYdF5UiaXnI7UrbQ0nzc',
    appId: '1:838682859343:ios:a8d8d21a32cf6e311e973a',
    messagingSenderId: '838682859343',
    projectId: 'na-hive-pg',
    databaseURL: 'https://na-hive-pg-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'na-hive-pg.appspot.com',
    iosBundleId: 'com.example.naHiveBloc',
  );
}
